// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:69956cdb-8f1a-4eaf-a0d0-479532c74b59",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_zN01FG9vu",
    "aws_user_pools_web_client_id": "6ap2mlqv16qa4hjikali0dfvch",
    "aws_user_files_s3_bucket": "bizxcess",
    "aws_user_files_s3_bucket_region": "ap-southeast-1"
};
export default awsmobile;
